---
upload_path: "/site//static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: admin/
webhook_url: https://hooks.slack.com/services/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
sections:
  highlight:
    default_front_matter_template: highlight
version: 0.38.1
