baseurl = "/"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode = "en-us"
languageLang = "en"
title = "Derek Odegard"
[[menu.main]]
name = "Food"
url = "/food"
weight = 2
[[menu.main]]
name = "About"
url = "/about"
weight = 1
